### PR TITLE
[FLINK-23346] Avoid core dump when rethrowing the exception

### PR DESCRIPTION
**Pull request by Zakelly**
This fixes [FLINK-23346](https://issues.apache.org/jira/browse/FLINK-23346)

### CODE REVIEW

**Comment by Zakelly** [comment]
@Myasuka @fredia @masteryhx Hi, would you please review this simple one? Thanks

**Comment by Myasuka** [comment]
It seems the CIs are broken..

**Comment by Zakelly** [comment]
> It seems the CIs are broken..

Hi @Myasuka , I repair the CI in 6.20.3. PR is here (https://github.com/ververica/frocksdb/pull/71). PTAL thanks.

And it seems the 8.5.3 branch will be abandoned since the community will try rocksdb 8.9.0. I will prepare my PR fixing FLINK-23346 after the CI is fixed by #71 . Afterwards this can be picked to branch 8.9.0 once it is ready.

**Comment by Zakelly** [comment]
Closing this and moving to branch 6.20.3.

**Pull request closed without merging**
