### PR TITLE
[FLINK-23346]Avoid core dump when rethrowing the exception

### PR DESCRIPTION
**Pull request by Zakelly**
This fixes [FLINK-23346](https://issues.apache.org/jira/browse/FLINK-23346)

### CODE REVIEW

**Comment by Zakelly** [comment]
@Myasuka I rework this on 6.20.3, PTAL thanks!

**Review by masteryhx — APPROVED** [review]
Thanks for the pr.
LGTM.

**Review by Myasuka — APPROVED** [review]
Sorry for the late review, LGTM.

**Review by JingGe — APPROVED** [review]
LGTM

**Pull request merged**
